// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxKeepVN.Infrastructure.Contexts;

#nullable disable

namespace TaxKeepVN.Infrastructure.Migrations
{
    [DbContext(typeof(TaxKeepDbContext))]
    [Migration("20260924111549_AddSystemLaw")]
    partial class AddSystemLaw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BirthCertNumber")
                        .HasColumnType("text")
                        .HasColumnName("birth_cert_number");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("CitizenId")
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_group");

                    b.Property<string>("EffectiveFromMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_from_month");

                    b.Property<string>("EffectiveToMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_to_month");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsProfileComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_profile_complete");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING_DOCUMENTS")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BirthCertNumber")
                        .HasDatabaseName("idx_dependents_birth_cert");

                    b.HasIndex("CitizenId")
                        .HasDatabaseName("idx_dependents_citizen_id");

                    b.HasIndex("TaxpayerId")
                        .HasDatabaseName("idx_dependents_taxpayer_id");

                    b.ToTable("dependents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DependentId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependent_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_type");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_mime_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readable");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("DependentId");

                    b.ToTable("dependent_documents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocumentRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RuleId");

                    b.HasIndex("TargetGroup", "DocType")
                        .IsUnique()
                        .HasDatabaseName("uq_group_doc_rule");

                    b.ToTable("dependent_document_rules", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyTaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("TaxWithheld")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_withheld");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_income");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaxpayerId");

                    b.ToTable("income_sources", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangeOp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("ApplyBasis")
                        .HasColumnType("jsonb")
                        .HasColumnName("apply_basis");

                    b.Property<DateOnly?>("ApplyFrom")
                        .HasColumnType("date")
                        .HasColumnName("apply_from");

                    b.Property<DateOnly?>("ApplyTo")
                        .HasColumnType("date")
                        .HasColumnName("apply_to");

                    b.Property<string>("Article")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("article");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid>("ChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<string>("Clause")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clause");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<string>("ConflictState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NONE")
                        .HasColumnName("conflict_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("decision");

                    b.Property<bool>("EditedByAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("edited_by_admin");

                    b.Property<string>("EvidenceText")
                        .HasColumnType("text")
                        .HasColumnName("evidence_text");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("flags");

                    b.Property<bool>("NewCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("new_code");

                    b.Property<string>("OpKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("op_key");

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("op_type");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AI")
                        .HasColumnName("origin");

                    b.Property<int?>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.Property<string>("Point")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("point");

                    b.Property<string>("ProposedDefinition")
                        .HasColumnType("jsonb")
                        .HasColumnName("proposed_definition");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChangesetId", "Decision")
                        .HasDatabaseName("idx_law_change_ops_changeset");

                    b.ToTable("law_change_ops", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangeset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ai_error_code");

                    b.Property<string>("AiErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("ai_error_message");

                    b.Property<string>("AiModel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ai_model");

                    b.Property<string>("AiRawResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_raw_response");

                    b.Property<Guid?>("AiTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_task_id");

                    b.Property<string>("AiWarnings")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_warnings");

                    b.Property<int>("BaseRevisionNo")
                        .HasColumnType("integer")
                        .HasColumnName("base_revision_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<Guid?>("MergedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_by");

                    b.Property<int?>("MergedRevisionNo")
                        .HasColumnType("integer")
                        .HasColumnName("merged_revision_no");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AI")
                        .HasColumnName("origin");

                    b.Property<int?>("PagesRead")
                        .HasColumnType("integer")
                        .HasColumnName("pages_read");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("EXTRACTING")
                        .HasColumnName("status");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AiTaskId")
                        .IsUnique()
                        .HasDatabaseName("uq_law_changesets_ai_task_id")
                        .HasFilter("ai_task_id IS NOT NULL");

                    b.HasIndex("DocumentId");

                    b.ToTable("law_changesets", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangesetRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<string>("ConflictDetail")
                        .HasColumnType("jsonb")
                        .HasColumnName("conflict_detail");

                    b.Property<string>("ConflictState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NONE")
                        .HasColumnName("conflict_state");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("decision");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("EvidenceText")
                        .HasColumnType("text")
                        .HasColumnName("evidence_text");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AI")
                        .HasColumnName("origin");

                    b.Property<string>("RelationKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation_key");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("relation_type");

                    b.Property<string>("SourceArticle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_article");

                    b.Property<string>("SourceClause")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_clause");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourcePoint")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_point");

                    b.Property<string>("TargetArticle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_article");

                    b.Property<string>("TargetClause")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_clause");

                    b.Property<Guid?>("TargetDocId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_doc_id");

                    b.Property<string>("TargetDocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_document_number");

                    b.Property<string>("TargetPoint")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_point");

                    b.HasKey("Id");

                    b.HasIndex("ChangesetId");

                    b.HasIndex("TargetDocId");

                    b.ToTable("law_changeset_relations", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawOrphanResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid>("ChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<Guid?>("GeneratedOpId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_op_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedOpId");

                    b.HasIndex("VersionId");

                    b.HasIndex("ChangesetId", "VersionId")
                        .IsUnique()
                        .HasDatabaseName("uq_orphan_resolution_changeset_version");

                    b.ToTable("law_orphan_resolutions", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRevision", b =>
                {
                    b.Property<int>("RevisionNo")
                        .HasColumnType("integer")
                        .HasColumnName("revision_no");

                    b.Property<Guid>("ChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("CommittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("committed_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<long>("MetaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("meta_version");

                    b.HasKey("RevisionNo");

                    b.HasIndex("ChangesetId")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.ToTable("law_revisions", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRuleDefinition", b =>
                {
                    b.Property<string>("RuleCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("RequiredForFlow3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("required_for_flow3");

                    b.Property<int?>("RequiredFromTaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("required_from_tax_year");

                    b.Property<string>("RuleGroup")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rule_group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_kind");

                    b.HasKey("RuleCode");

                    b.ToTable("law_rule_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            RuleCode = "PIT_TAX_SCHEDULE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/year",
                            Description = "Bậc thuế, ngưỡng thu nhập tính thuế và thuế suất từng bậc",
                            DisplayName = "Biểu thuế lũy tiến từng phần (tiền lương, tiền công)",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RuleGroup = "SCHEDULE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "SCHEDULE"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_PERSONAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/month",
                            Description = "Mức giảm trừ gia cảnh cho chính người nộp thuế mỗi tháng",
                            DisplayName = "Giảm trừ bản thân",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_DEPENDENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/person/month",
                            Description = "Mức giảm trừ cho mỗi người phụ thuộc hợp lệ mỗi tháng",
                            DisplayName = "Giảm trừ mỗi người phụ thuộc",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_DEPENDENT_GROUPS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nhóm người phụ thuộc hợp lệ, độ tuổi, điều kiện khuyết tật, học tập và thu nhập",
                            DisplayName = "Nhóm người phụ thuộc và điều kiện",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RuleGroup = "DEPENDENT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "JSON"
                        },
                        new
                        {
                            RuleCode = "PIT_DEPENDENT_MAX_MONTHLY_INCOME",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/month",
                            Description = "Ngưỡng thu nhập bình quân tháng tối đa để đủ điều kiện làm người phụ thuộc",
                            DisplayName = "Thu nhập bình quân tháng tối đa của người phụ thuộc",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RuleGroup = "DEPENDENT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_MEDICAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/year",
                            Description = "Mức giảm trừ chi phí khám chữa bệnh hiểm nghèo tối đa trong năm",
                            DisplayName = "Giảm trừ chi phí y tế",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RequiredFromTaxYear = 2026,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_EDUCATION",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/year",
                            Description = "Mức giảm trừ chi phí học tập, đào tạo cho bản thân và người phụ thuộc tối đa trong năm",
                            DisplayName = "Giảm trừ chi phí giáo dục, đào tạo",
                            IsActive = true,
                            RequiredForFlow3 = true,
                            RequiredFromTaxYear = 2026,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_MANDATORY_INSURANCE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cho phép trừ các khoản đóng bảo hiểm bắt buộc (BHXH, BHYT, BHTN) theo thực tế phát sinh",
                            DisplayName = "Trừ bảo hiểm bắt buộc theo thực đóng",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "FLAG"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_VOLUNTARY_INSURANCE_CAP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/month",
                            Description = "Mức đóng vào quỹ hưu trí tự nguyện, bảo hiểm bổ sung được trừ tối đa mỗi tháng",
                            DisplayName = "Trần trừ bảo hiểm hưu trí bổ sung, tự nguyện, nhân thọ",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_DEDUCTION_CHARITY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cho phép trừ các khoản đóng góp từ thiện, nhân đạo, khuyến học theo thực tế phát sinh",
                            DisplayName = "Trừ đóng góp từ thiện, nhân đạo, khuyến học",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "DEDUCTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "FLAG"
                        },
                        new
                        {
                            RuleCode = "PIT_SETTLEMENT_SELF_REQUIRED_IF_MED_EDU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cờ xác định cá nhân có áp dụng giảm trừ y tế hoặc giáo dục thì bắt buộc phải tự quyết toán trực tiếp",
                            DisplayName = "Có giảm trừ y tế, giáo dục thì phải tự quyết toán",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "SETTLEMENT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "FLAG"
                        },
                        new
                        {
                            RuleCode = "PIT_WITHHOLD_CASUAL_RATE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "%",
                            Description = "Tỷ lệ khấu trừ thuế TNCN tại nguồn đối với cá nhân không ký HĐLĐ hoặc HĐLĐ dưới 3 tháng",
                            DisplayName = "Tỷ lệ khấu trừ lao động vãng lai",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "WITHHOLDING",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "RATE"
                        },
                        new
                        {
                            RuleCode = "PIT_WITHHOLD_CASUAL_MIN_PAYMENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "VND/payment",
                            Description = "Mức chi trả từ ngưỡng này trở lên mỗi lần thì phải khấu trừ thuế vãng lai",
                            DisplayName = "Ngưỡng mỗi lần chi trả phải khấu trừ",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "WITHHOLDING",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "AMOUNT"
                        },
                        new
                        {
                            RuleCode = "PIT_RATE_NON_RESIDENT_SALARY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultUnit = "%",
                            Description = "Thuế suất thuế TNCN đối với thu nhập từ tiền lương, tiền công của cá nhân không cư trú",
                            DisplayName = "Thuế suất tiền lương cá nhân không cư trú",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "RATE",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "RATE"
                        },
                        new
                        {
                            RuleCode = "PIT_EXEMPTION_OVERTIME",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phần tiền lương, tiền công trả cao hơn do làm việc ban đêm, làm thêm giờ được miễn thuế",
                            DisplayName = "Miễn thuế phần làm đêm, thêm giờ",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "EXEMPTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "TEXT"
                        },
                        new
                        {
                            RuleCode = "PIT_EXEMPTION_RETIREMENT_PENSION",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiền lương hưu do Quỹ bảo hiểm xã hội chi trả được miễn thuế TNCN",
                            DisplayName = "Miễn thuế lương hưu từ Quỹ BHXH",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "EXEMPTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "TEXT"
                        },
                        new
                        {
                            RuleCode = "PIT_EXEMPTION_INSURANCE_COMPENSATION",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiền bồi thường bảo hiểm con người, tài sản, trợ cấp tai nạn lao động được miễn thuế TNCN",
                            DisplayName = "Miễn thuế bồi thường bảo hiểm, trợ cấp tai nạn lao động",
                            IsActive = true,
                            RequiredForFlow3 = false,
                            RuleGroup = "EXEMPTION",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueKind = "TEXT"
                        });
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ApplyFrom")
                        .HasColumnType("date")
                        .HasColumnName("apply_from");

                    b.Property<DateOnly?>("ApplyTo")
                        .HasColumnType("date")
                        .HasColumnName("apply_to");

                    b.Property<string>("Article")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("article");

                    b.Property<string>("Clause")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clause");

                    b.Property<int>("CreatedInRevision")
                        .HasColumnType("integer")
                        .HasColumnName("created_in_revision");

                    b.Property<Guid?>("DerivedFromVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("derived_from_version_id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("EvidenceText")
                        .HasColumnType("text")
                        .HasColumnName("evidence_text");

                    b.Property<int?>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.Property<string>("Point")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("point");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<string>("RuleValue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_value");

                    b.Property<Guid?>("SourceOpId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_op_id");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<int?>("SupersededInRevision")
                        .HasColumnType("integer")
                        .HasColumnName("superseded_in_revision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInRevision");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SourceOpId");

                    b.HasIndex("SupersededInRevision");

                    b.HasIndex("RuleCode", "ApplyFrom")
                        .HasDatabaseName("idx_law_rule_versions_active")
                        .HasFilter("superseded_in_revision IS NULL");

                    b.ToTable("law_rule_versions", null, t =>
                        {
                            t.HasCheckConstraint("chk_law_rule_versions_apply_range", "apply_to IS NULL OR apply_to > apply_from");
                        });
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_type");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsPlaceholder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_placeholder");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("Issuer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("issuer");

                    b.Property<string>("LegalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("CHUA_RO")
                        .HasColumnName("legal_status");

                    b.Property<string>("LegalStatusNote")
                        .HasColumnType("text")
                        .HasColumnName("legal_status_note");

                    b.Property<string>("NumberNormalized")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number_normalized");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NumberNormalized")
                        .IsUnique()
                        .HasDatabaseName("uq_legal_documents_normalized")
                        .HasFilter("number_normalized IS NOT NULL");

                    b.ToTable("legal_documents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LegalDocumentRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CreatedInRevision")
                        .HasColumnType("integer")
                        .HasColumnName("created_in_revision");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("EvidenceText")
                        .HasColumnType("text")
                        .HasColumnName("evidence_text");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("relation_type");

                    b.Property<string>("SourceArticle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_article");

                    b.Property<string>("SourceClause")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_clause");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourcePoint")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_point");

                    b.Property<string>("TargetArticle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_article");

                    b.Property<string>("TargetClause")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_clause");

                    b.Property<Guid>("TargetDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_document_id");

                    b.Property<string>("TargetPoint")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_point");

                    b.HasKey("Id");

                    b.HasIndex("CreatedInRevision");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("TargetDocumentId")
                        .HasDatabaseName("idx_legal_doc_rel_target");

                    b.ToTable("legal_document_relations", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .HasDatabaseName("idx_revoked_tokens_jti");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.SystemNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_type");

                    b.Property<string>("TargetActionUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_action_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("system_notifications", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("taxpayer")
                        .HasColumnName("user_role");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_citizen_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TaxpayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocument", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Dependent", "Dependent")
                        .WithMany("Documents")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependent");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.IncomeSource", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TaxpayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangeOp", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawChangeset", "Changeset")
                        .WithMany("Ops")
                        .HasForeignKey("ChangesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Changeset");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangeset", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LegalDocument", "Document")
                        .WithMany("Changesets")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangesetRelation", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawChangeset", "Changeset")
                        .WithMany("Relations")
                        .HasForeignKey("ChangesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LegalDocument", "TargetDocument")
                        .WithMany()
                        .HasForeignKey("TargetDocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Changeset");

                    b.Navigation("TargetDocument");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawOrphanResolution", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawChangeset", "Changeset")
                        .WithMany("OrphanResolutions")
                        .HasForeignKey("ChangesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawChangeOp", "GeneratedOp")
                        .WithMany()
                        .HasForeignKey("GeneratedOpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawRuleVersion", "RuleVersion")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Changeset");

                    b.Navigation("GeneratedOp");

                    b.Navigation("RuleVersion");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRevision", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawChangeset", "Changeset")
                        .WithOne("Revision")
                        .HasForeignKey("TaxKeepVN.Domain.Entities.Law.LawRevision", "ChangesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LegalDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Changeset");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRuleVersion", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawRevision", "Revision")
                        .WithMany("RuleVersionsCreated")
                        .HasForeignKey("CreatedInRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LegalDocument", "Document")
                        .WithMany("RuleVersions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawRuleDefinition", "RuleDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("RuleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawChangeOp", "SourceOp")
                        .WithMany()
                        .HasForeignKey("SourceOpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawRevision", "SupersededRevision")
                        .WithMany("RuleVersionsSuperseded")
                        .HasForeignKey("SupersededInRevision")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("Revision");

                    b.Navigation("RuleDefinition");

                    b.Navigation("SourceOp");

                    b.Navigation("SupersededRevision");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LegalDocumentRelation", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LawRevision", "Revision")
                        .WithMany("DocumentRelationsCreated")
                        .HasForeignKey("CreatedInRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LegalDocument", "SourceDocument")
                        .WithMany("SourceRelations")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Law.LegalDocument", "TargetDocument")
                        .WithMany("TargetRelations")
                        .HasForeignKey("TargetDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Revision");

                    b.Navigation("SourceDocument");

                    b.Navigation("TargetDocument");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.SystemNotification", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawChangeset", b =>
                {
                    b.Navigation("Ops");

                    b.Navigation("OrphanResolutions");

                    b.Navigation("Relations");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRevision", b =>
                {
                    b.Navigation("DocumentRelationsCreated");

                    b.Navigation("RuleVersionsCreated");

                    b.Navigation("RuleVersionsSuperseded");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LawRuleDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Law.LegalDocument", b =>
                {
                    b.Navigation("Changesets");

                    b.Navigation("RuleVersions");

                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
