// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxKeepVN.Infrastructure.Contexts;

#nullable disable

namespace TaxKeepVN.Infrastructure.Migrations
{
    [DbContext(typeof(TaxKeepDbContext))]
    [Migration("20260917051321_UpdateDocumentToBelongToTaxPeriodOnly")]
    partial class UpdateDocumentToBelongToTaxPeriodOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BirthCertNumber")
                        .HasColumnType("text")
                        .HasColumnName("birth_cert_number");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BirthDate");

                    b.Property<string>("CitizenId")
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CurrentGroup");

                    b.Property<string>("EffectiveFromMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_from_month");

                    b.Property<string>("EffectiveToMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_to_month");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsProfileComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsProfileComplete");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING_DOCUMENTS")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BirthCertNumber")
                        .HasDatabaseName("idx_dependents_birth_cert");

                    b.HasIndex("CitizenId")
                        .HasDatabaseName("idx_dependents_citizen_id");

                    b.HasIndex("TaxpayerId")
                        .HasDatabaseName("idx_dependents_taxpayer_id");

                    b.ToTable("dependents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DependentId");

                    b.ToTable("DependentDocuments");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocumentRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RuleId");

                    b.HasIndex("TargetGroup", "DocType")
                        .IsUnique()
                        .HasDatabaseName("uq_group_doc_rule");

                    b.ToTable("dependent_document_rules", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("text")
                        .HasColumnName("buyer_address");

                    b.Property<string>("BuyerIdCard")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("buyer_id_card");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerTaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("buyer_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type_code");

                    b.Property<short?>("ExtractedYear")
                        .HasColumnType("smallint")
                        .HasColumnName("extracted_year");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("InvoiceSeries")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_series");

                    b.Property<bool?>("IsIdentityValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_identity_valid");

                    b.Property<bool?>("IsYearValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_year_valid");

                    b.Property<string>("LookupCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lookup_code");

                    b.Property<string>("LookupUrl")
                        .HasColumnType("text")
                        .HasColumnName("lookup_url");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("SellerAddress")
                        .HasColumnType("text")
                        .HasColumnName("seller_address");

                    b.Property<string>("SellerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seller_phone");

                    b.Property<string>("SellerTaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seller_tax_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UPLOADED")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TotalAmountInWords")
                        .HasColumnType("text")
                        .HasColumnName("total_amount_in_words");

                    b.HasKey("Id");

                    b.HasIndex("DocTypeCode")
                        .HasDatabaseName("idx_documents_doc_type_code");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("idx_documents_period_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DocumentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_name");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("integer")
                        .HasColumnName("item_order");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_price");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_document_items_document_id");

                    b.ToTable("document_items", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyTaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("TaxWithheld")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_withheld");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_income");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("income_sources");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .HasDatabaseName("idx_revoked_tokens_jti");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.SystemNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_type");

                    b.Property<string>("TargetActionUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_action_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.ToTable("system_notifications");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxDocumentType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsTaxEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_tax_eligible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("document_types", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "SALES_INVOICE",
                            IsTaxEligible = true,
                            Name = "Hóa đơn bán hàng"
                        },
                        new
                        {
                            Code = "VAT_INVOICE",
                            IsTaxEligible = true,
                            Name = "Hóa đơn GTGT"
                        },
                        new
                        {
                            Code = "WITHHOLDING_VOUCHER",
                            IsTaxEligible = true,
                            Name = "Chứng từ khấu trừ thuế TNCN"
                        });
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<short>("TaxYear")
                        .HasColumnType("smallint")
                        .HasColumnName("tax_year");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tax_periods_user_id");

                    b.HasIndex("UserId", "TaxYear")
                        .IsUnique()
                        .HasDatabaseName("uq_tax_periods_user_year");

                    b.ToTable("tax_periods", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("taxpayer")
                        .HasColumnName("user_role");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_citizen_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocument", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Dependent", "Dependent")
                        .WithMany("Documents")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependent");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Document", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.TaxDocumentType", "DocType")
                        .WithMany("Documents")
                        .HasForeignKey("DocTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.TaxPeriod", "Period")
                        .WithMany("Documents")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocType");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DocumentItem", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Document", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxPeriod", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithMany("TaxPeriods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Document", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxDocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxPeriod", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.User", b =>
                {
                    b.Navigation("TaxPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
