// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxKeepVN.Infrastructure.Contexts;

#nullable disable

namespace TaxKeepVN.Infrastructure.Migrations
{
    [DbContext(typeof(TaxKeepDbContext))]
    [Migration("20261010043959_AddIncomeYearToDocuments")]
    partial class AddIncomeYearToDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovalDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_deadline");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("booking_code");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("ExpertSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_slot_id");

                    b.Property<decimal>("Fee")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("fee");

                    b.Property<DateTimeOffset>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_reference");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_description");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("NONE")
                        .HasColumnName("refund_status");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("session_type");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer")
                        .HasColumnName("specialization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PENDING_PAYMENT")
                        .HasColumnName("status");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("topic_title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique()
                        .HasDatabaseName("uq_bookings_booking_code");

                    b.HasIndex("ExpertSlotId")
                        .HasDatabaseName("idx_bookings_slot_id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_bookings_user_id");

                    b.HasIndex("Status", "HoldExpiresAt")
                        .HasDatabaseName("idx_bookings_status_hold");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.BookingAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("idx_booking_attachments_booking_id");

                    b.ToTable("booking_attachments", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ConsultationFeeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_fee");

                    b.Property<decimal>("MinFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_fee");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("session_type");

                    b.HasKey("Id");

                    b.HasIndex("SessionType", "DurationMinutes")
                        .IsUnique()
                        .HasDatabaseName("uq_consultation_fee_type_duration");

                    b.ToTable("consultation_fee_configurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 30,
                            IsActive = true,
                            MaxFee = 1000000m,
                            MinFee = 100000m,
                            SessionType = "ONLINE_MEETING"
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 60,
                            IsActive = true,
                            MaxFee = 2000000m,
                            MinFee = 200000m,
                            SessionType = "ONLINE_MEETING"
                        });
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BirthCertNumber")
                        .HasColumnType("text")
                        .HasColumnName("birth_cert_number");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("CitizenId")
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_group");

                    b.Property<string>("EffectiveFromMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_from_month");

                    b.Property<string>("EffectiveToMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_to_month");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsProfileComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_profile_complete");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING_DOCUMENTS")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BirthCertNumber")
                        .HasDatabaseName("idx_dependents_birth_cert");

                    b.HasIndex("CitizenId")
                        .HasDatabaseName("idx_dependents_citizen_id");

                    b.HasIndex("TaxpayerId")
                        .HasDatabaseName("idx_dependents_taxpayer_id");

                    b.ToTable("dependents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DependentId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependent_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_type");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_mime_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readable");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("DependentId")
                        .HasDatabaseName("idx_dependent_documents_dependent_id");

                    b.ToTable("dependent_documents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocumentRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RuleId");

                    b.HasIndex("TargetGroup", "DocType")
                        .IsUnique()
                        .HasDatabaseName("uq_group_doc_rule");

                    b.ToTable("dependent_document_rules", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("text")
                        .HasColumnName("buyer_address");

                    b.Property<string>("BuyerIdCard")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("buyer_id_card");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerTaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("buyer_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type_code");

                    b.Property<short?>("ExtractedYear")
                        .HasColumnType("smallint")
                        .HasColumnName("extracted_year");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<int?>("IncomeYear")
                        .HasColumnType("integer")
                        .HasColumnName("income_year");

                    b.Property<decimal?>("InsuranceDeducted")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("insurance_deducted");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("InvoiceSeries")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_series");

                    b.Property<bool?>("IsIdentityValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_identity_valid");

                    b.Property<bool?>("IsNotReimbursed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_not_reimbursed");

                    b.Property<bool?>("IsYearValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_year_valid");

                    b.Property<string>("LookupCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lookup_code");

                    b.Property<string>("LookupUrl")
                        .HasColumnType("text")
                        .HasColumnName("lookup_url");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("SellerAddress")
                        .HasColumnType("text")
                        .HasColumnName("seller_address");

                    b.Property<string>("SellerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seller_phone");

                    b.Property<string>("SellerTaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seller_tax_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UPLOADED")
                        .HasColumnName("status");

                    b.Property<decimal?>("TaxWithheld")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_withheld");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TotalAmountInWords")
                        .HasColumnType("text")
                        .HasColumnName("total_amount_in_words");

                    b.Property<decimal?>("TotalIncome")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_income");

                    b.HasKey("Id");

                    b.HasIndex("DocTypeCode")
                        .HasDatabaseName("idx_documents_doc_type_code");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("idx_documents_period_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DocumentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_name");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("integer")
                        .HasColumnName("item_order");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_price");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_document_items_document_id");

                    b.ToTable("document_items", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("application_number");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPosition")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("current_position");

                    b.Property<string>("ExperienceDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("experience_description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_title");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SupplementRequestReason")
                        .HasColumnType("text")
                        .HasColumnName("supplement_request_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsOfExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_expert_applications_number");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_expert_applications_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_active_pending_application")
                        .HasFilter("status IN ('PendingReview', 'NeedSupplement')");

                    b.ToTable("expert_applications", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("idx_expert_audits_application_id");

                    b.ToTable("expert_application_audits", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("certificate_name");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("certificate_number");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("certificate_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FileMimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_mime_type");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("HasExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_expiry");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("VerificationNote")
                        .HasColumnType("text")
                        .HasColumnName("verification_note");

                    b.Property<string>("VerificationSource")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("verification_source");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PendingVerification")
                        .HasColumnName("verification_status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("idx_expert_certs_application_id");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("expert_application_certificates", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationFeeProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("ProposedFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("proposed_fee");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("session_type");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "SessionType", "DurationMinutes")
                        .IsUnique()
                        .HasDatabaseName("uq_application_fee_proposal");

                    b.ToTable("expert_application_fee_proposals", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationSpecialization", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer")
                        .HasColumnName("specialization_id");

                    b.HasKey("ApplicationId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("expert_application_specializations", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<int>("CompletedConsultationsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_consultations_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_title");

                    b.Property<Guid>("LatestApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_application_id");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_reviews");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsOfExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("LatestApplicationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_expert_profiles_user_id");

                    b.ToTable("expert_profiles", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<bool>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_anonymous");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpertProfileId")
                        .HasDatabaseName("idx_expert_reviews_profile_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_expert_reviews_user_id");

                    b.ToTable("expert_reviews", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<Guid?>("HoldUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_booked");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("ONLINE_MEETING")
                        .HasColumnName("session_type");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date")
                        .HasColumnName("slot_date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpertProfileId")
                        .HasDatabaseName("idx_expert_slots_profile_id");

                    b.HasIndex("SlotDate")
                        .HasDatabaseName("idx_expert_slots_slot_date");

                    b.HasIndex("ExpertProfileId", "SlotDate", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uq_expert_slots_profile_datetime");

                    b.ToTable("expert_slots", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InsuranceDeducted")
                        .HasColumnType("numeric")
                        .HasColumnName("insurance_deducted");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("organization_name");

                    b.Property<string>("PayslipFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("payslip_file_url");

                    b.Property<decimal>("TaxAlreadyDeducted")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_already_deducted");

                    b.Property<string>("TaxIdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id_number");

                    b.Property<decimal>("TotalTaxableIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_taxable_income");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_incomes_user_id");

                    b.ToTable("incomes", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyTaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InsuranceDeducted")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("insurance_deducted");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("TaxWithheld")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_withheld");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_income");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("income_sources");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .HasDatabaseName("idx_revoked_tokens_jti");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_roles_code");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "taxpayer",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Người dùng cá nhân thực hiện quyết toán, kê khai thuế",
                            IsActive = true,
                            Name = "Người nộp thuế"
                        },
                        new
                        {
                            Id = 2,
                            Code = "admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quản trị viên quản lý toàn bộ hệ thống, thẩm định hồ sơ",
                            IsActive = true,
                            Name = "Quản trị viên hệ thống"
                        },
                        new
                        {
                            Id = 3,
                            Code = "expert",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Chuyên gia đã được phê duyệt, cung cấp dịch vụ tư vấn thuế",
                            IsActive = true,
                            Name = "Chuyên gia tư vấn thuế"
                        });
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_specializations_code");

                    b.ToTable("specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PIT",
                            IsActive = true,
                            Name = "Thuế thu nhập cá nhân (TNCN)"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CIT",
                            IsActive = true,
                            Name = "Thuế thu nhập doanh nghiệp (TNDN)"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FINALIZATION",
                            IsActive = true,
                            Name = "Quyết toán thuế"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TAX_REFUND",
                            IsActive = true,
                            Name = "Hoàn thuế"
                        },
                        new
                        {
                            Id = 5,
                            Code = "INTERNAL_ACCOUNTING",
                            IsActive = true,
                            Name = "Kế toán nội bộ"
                        },
                        new
                        {
                            Id = 6,
                            Code = "TRANSFER_PRICING",
                            IsActive = true,
                            Name = "Chuyển giá"
                        },
                        new
                        {
                            Id = 7,
                            Code = "TAX_AGENT",
                            IsActive = true,
                            Name = "Đại lý thuế"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CORPORATE_TAX_LEGAL",
                            IsActive = true,
                            Name = "Pháp lý thuế doanh nghiệp"
                        });
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<int?>("AppliesFromYear")
                        .HasColumnType("integer")
                        .HasColumnName("applies_from_year");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigKey", "AppliesFromYear")
                        .IsUnique()
                        .HasDatabaseName("uq_system_configs_key_year");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.SystemNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_type");

                    b.Property<string>("TargetActionUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_action_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.ToTable("system_notifications");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxDocumentType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsTaxEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_tax_eligible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<short>("TaxYear")
                        .HasColumnType("smallint")
                        .HasColumnName("tax_year");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tax_periods_user_id");

                    b.HasIndex("UserId", "TaxYear")
                        .IsUnique()
                        .HasDatabaseName("uq_tax_periods_user_year");

                    b.ToTable("tax_periods", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxSettlementDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppliedBracketNo")
                        .HasColumnType("integer")
                        .HasColumnName("applied_bracket_no");

                    b.Property<decimal>("CharityDeduction")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("charity_deduction");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("CutoffDate")
                        .HasColumnType("date")
                        .HasColumnName("cutoff_date");

                    b.Property<string>("DeductionConfigSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("deduction_config_snapshot");

                    b.Property<decimal>("DependentDeductionAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("dependent_deduction_amount");

                    b.Property<int>("DependentDeductionPersonMonths")
                        .HasColumnType("integer")
                        .HasColumnName("dependent_deduction_person_months");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("due_amount");

                    b.Property<decimal>("EducationDeduction")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("education_deduction");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<decimal>("MedicalDeduction")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("medical_deduction");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("PersonalDeductionAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("personal_deduction_amount");

                    b.Property<int>("PersonalDeductionMonths")
                        .HasColumnType("integer")
                        .HasColumnName("personal_deduction_months");

                    b.Property<string>("PitBracketsSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("pit_brackets_snapshot");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxPayable")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_payable");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.Property<decimal>("TaxableIncomeMonthly")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("taxable_income_monthly");

                    b.Property<decimal>("TaxableIncomeYearly")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("taxable_income_yearly");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxpayer_id");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_deductions");

                    b.Property<decimal>("TotalGrossIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_gross_income");

                    b.Property<decimal>("TotalInsuranceDeduction")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_insurance_deduction");

                    b.Property<decimal>("TotalTaxWithheld")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_tax_withheld");

                    b.Property<string>("ZipFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("zip_file_url");

                    b.HasKey("Id");

                    b.HasIndex("TaxpayerId", "TaxYear")
                        .HasDatabaseName("idx_settlement_taxpayer_year");

                    b.ToTable("tax_settlement_dossiers", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxSettlementIncomeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyTaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_tax_code");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<decimal>("GrossIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_income");

                    b.Property<Guid>("IncomeSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("income_source_id");

                    b.Property<decimal>("InsuranceDeduction")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("insurance_deduction");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_selected");

                    b.Property<decimal>("TaxWithheld")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_withheld");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("tax_settlement_income_items", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_id_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("taxpayer")
                        .HasColumnName("user_role");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_citizen_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertSlot", "ExpertSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("ExpertSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Bookings")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertSlot");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.BookingAttachment", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Booking", "Booking")
                        .WithMany("Attachments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DependentDocument", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Dependent", "Dependent")
                        .WithMany("Documents")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependent");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Document", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.TaxDocumentType", "DocType")
                        .WithMany("Documents")
                        .HasForeignKey("DocTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxKeepVN.Domain.Entities.TaxPeriod", "Period")
                        .WithMany("Documents")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocType");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.DocumentItem", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Document", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplication", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithMany("ExpertApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationAudit", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertApplication", "Application")
                        .WithMany("Audits")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationCertificate", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertApplication", "Application")
                        .WithMany("Certificates")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.User", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationFeeProposal", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertApplication", "Application")
                        .WithMany("FeeProposals")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplicationSpecialization", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertApplication", "Application")
                        .WithMany("ApplicationSpecializations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.Specialization", "Specialization")
                        .WithMany("ApplicationSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertProfile", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertApplication", "LatestApplication")
                        .WithMany()
                        .HasForeignKey("LatestApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithOne("ExpertProfile")
                        .HasForeignKey("TaxKeepVN.Domain.Entities.ExpertProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LatestApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertReview", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithMany("ExpertReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertSlot", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("Slots")
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Income", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxPeriod", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.User", "User")
                        .WithMany("TaxPeriods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxSettlementIncomeItem", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.TaxSettlementDossier", "Dossier")
                        .WithMany("IncomeItems")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.User", b =>
                {
                    b.HasOne("TaxKeepVN.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Dependent", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Document", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertApplication", b =>
                {
                    b.Navigation("ApplicationSpecializations");

                    b.Navigation("Audits");

                    b.Navigation("Certificates");

                    b.Navigation("FeeProposals");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertProfile", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.ExpertSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("ApplicationSpecializations");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxDocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxPeriod", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.TaxSettlementDossier", b =>
                {
                    b.Navigation("IncomeItems");
                });

            modelBuilder.Entity("TaxKeepVN.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ExpertApplications");

                    b.Navigation("ExpertProfile");

                    b.Navigation("ExpertReviews");

                    b.Navigation("TaxPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
